#ifndef ESCPOSPRINTER_ERROR_H
#define ESCPOSPRINTER_ERROR_H

typedef enum escpos_error {
    ESCPOS_ERROR_NONE = 0,

    ESCPOS_ERROR_SOCK,
    ESCPOS_ERROR_INVALID_ADDR,
    ESCPOS_ERROR_CONNECTION_FAILED,
    ESCPOS_ERROR_SEND_FAILED,
    ESCPOS_ERROR_IMAGE_UPLOAD_FAILED,
    ESCPOS_ERROR_IMAGE_PRINT_FAILED,
    ESCPOS_ERROR_INVALID_CONFIG
} escpos_error;

extern escpos_error escpos_last_error();

#endif
